### PR TITLE
Updated ClojureScript version and Om version

### PR DESCRIPTION
**Pull request by bensu**
By updating to the latest ClojureScript and Om versions, it is not necessary to add React in index.html, the new :foreign-libs functionality handles. I tried some basic functionality with Om and it worked both in the dev and min builds.

Hope this helps.

### CODE REVIEW

**Comment by bhauman** [comment]
Thanks for the updates.  I certainly can use the help :)

**Comment by bhauman** [comment]
You wouldn't happen to want to create minimal Om and Reagent templates that respond to some flags?

Perhaps just one flag --reagent.

**Comment by bensu** [comment]
I'll think about it, it sounds like a good idea. Do you want the Sablono dependency in both?

**Comment by bhauman** [comment]
I guess Sablono isn't needed for Reagent, so maybe exclude it as a dep.

Thanks for giving it some thought.

**Pull request merged**
