### PR TITLE
added rum as an option

### PR DESCRIPTION
**Pull request by boogie666**
Added the option to use [rum@0.10.2](https://github.com/tonsky/rum).

### CODE REVIEW

**Comment by bhauman** [comment]
Please add this to the README as well

**Comment by boogie666** [comment]
Done :)

**Comment by bhauman** [comment]
Sorry man, there are conflicts, please resolve ...

**Comment by boogie666** [comment]
Done

**Comment by bhauman** [comment]
dude,  I really don't know what to say ... now the comments are not in the maps they belong in. 
I'm closing this.

**Comment by bhauman** [comment]
I apologize for becoming impatient earlier, these things happen to all of us all the time... no hard feelings over on this end.  I have done this same thing and will do more than likely do it in the future.

I am not alone when I say I appreciate pull requests that work and don't require a bunch of  back and forth for small issues ...

**Comment by boogie666** [comment]
God damn it, i recently installed a plugin for atom that formats clojure, guess it does not handle this kind of stuff that well. Sorry, i fix this and submit a new pull request with a single commit that does not have all the issues. I'm sorry for this.

**Pull request closed without merging**
